### ISSUE TITLE
Page new and edit view cleanup and improvements

### ISSUE THREAD

**Issue by ghost** [rit-sse/wtf#11]
Modify the page new / edit views to look pretty and make sense.  It should probably have the following features:

~~\* Automatically determining the author of the page (more work on authentication / authorization needed for this first)~~
Let's worry about this for a later release. - ck
- Generating / displaying a default slug (short filename of the page used for URLs) when a page name is entered (ex: my-awesome-page for "My Awesome Page")
  - the default should also be modifiable
- Toggling entering a date for the published_at field
  - there should be some option to publish the page immediately or at a later date
  - only show the date entry field if the page is not published immediately

The edit content view should be switched to the ace editor for markdown but this task is tracked in issue #10.

**Comment by codykrieger** [comment]
Slug auto generation, validation, etc. is all working at this point. If you specify something in the slug field at the time of page creation (or editing), that will override the auto generated one.

I also moved page editing stuff to the /admin namespace. By convention, we should make any controllers in the /admin namespace be subclasses of AdminController, because they'll automatically inherit some authentication bits that we'll need in order to protect everything.
